# Generated by Django 3.1.7 on 2021-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COemail', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('COsubject', models.CharField(max_length=50, verbose_name='Subject')),
                ('COtype', models.CharField(choices=[('COMT', 'Complaint'), ('SUGGS', 'Suggestions'), ('LINR', 'Links Error'), ('REPR', 'Report a user'), ('PROS', 'Property rights'), ('OTHS', 'Others')], max_length=50, verbose_name='Message type')),
                ('COmessage', models.TextField(help_text="Reports an error or user , copy > paste the 'link' or 'user name' ", max_length=8000, verbose_name='Message')),
                ('COis_seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('COin_progress', models.BooleanField(default=False, verbose_name='In progress')),
                ('COslug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
