# Generated by Django 3.1.7 on 2021-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_cois_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABtitle', models.CharField(max_length=100, verbose_name='Title')),
                ('ABmain', models.TextField(max_length=15000, verbose_name='Main')),
                ('ABcreated_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ABon_page', models.BooleanField(default=False, verbose_name='View as main')),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='COcreated_dt',
            field=models.DateTimeField(auto_now_add=True,  verbose_name='Created at'),
        ),
    ]
