# Generated by Django 3.1.7 on 2021-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210519_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='COcreated_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
