# Generated by Django 3.1.7 on 2021-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210519_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ABis_arabic',
            field=models.BooleanField(default=False, verbose_name='Is arabic'),
        ),
    ]
