# Generated by Django 3.1.7 on 2021-04-05 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRbio', models.CharField(max_length=100, verbose_name='Address')),
                ('PRjoin_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='join date')),
                ('PRslug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('PRuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
