# Generated by Django 3.1.7 on 2021-03-17 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20210308_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CAref_img',
            field=models.URLField(max_length=500, null=True, verbose_name='Link image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRref',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Outside reference link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRref_img',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link image'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='SHnum',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='SHupdated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
