# Generated by Django 3.1.7 on 2021-05-03 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20210422_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator('0.1', message='Must be a postive number.')], verbose_name='Price'),
        ),
    ]
