# Generated by Django 3.1.7 on 2021-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_auto_20210516_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRcreated_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
           
        ),
    ]
